[package]
name = "forestgenerationthing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.19.1"
winit = "0.29.10"
env_logger = "0.10"
log = "0.4"
pollster = "0.3.0"
